#!/bin/sh
# Runtime config hook for the mina-explorer container.
#
# Runs before nginx starts via the nginx-unprivileged image's
# /docker-entrypoint.d/ mechanism. Reads MINA_EXPLORER_DEFAULT_NETWORK and
# MINA_EXPLORER_NETWORKS env vars and regenerates /usr/share/nginx/html/config.js
# so the SPA picks up the overrides at next page load.
#
# If neither env var is set, the bundled placeholder config.js is left alone
# and the explorer uses its compiled-in defaults — image behaves identically
# to the GitHub Pages build.

set -eu

CONFIG_FILE=/usr/share/nginx/html/config.js
DEFAULT_NETWORK="${MINA_EXPLORER_DEFAULT_NETWORK:-}"
NETWORKS_JSON="${MINA_EXPLORER_NETWORKS:-}"

if [ -z "$DEFAULT_NETWORK" ] && [ -z "$NETWORKS_JSON" ]; then
  echo "[mina-explorer] no MINA_EXPLORER_* env vars set; using compiled-in defaults"
  exit 0
fi

# Validate the network id is a simple identifier — embedded directly into JS
if [ -n "$DEFAULT_NETWORK" ]; then
  case "$DEFAULT_NETWORK" in
    *[!a-zA-Z0-9_-]*)
      echo "[mina-explorer] error: MINA_EXPLORER_DEFAULT_NETWORK='$DEFAULT_NETWORK' has invalid characters (allowed: a-zA-Z0-9_-)" >&2
      exit 1
      ;;
  esac
fi

# Validate JSON before embedding it raw into the config file
if [ -n "$NETWORKS_JSON" ]; then
  if ! printf '%s' "$NETWORKS_JSON" | jq -e . >/dev/null 2>&1; then
    echo "[mina-explorer] error: MINA_EXPLORER_NETWORKS is not valid JSON" >&2
    echo "[mina-explorer] received: $NETWORKS_JSON" >&2
    exit 1
  fi
else
  NETWORKS_JSON='{}'
fi

if [ -n "$DEFAULT_NETWORK" ]; then
  DEFAULT_JS="\"$DEFAULT_NETWORK\""
else
  DEFAULT_JS="undefined"
fi

cat > "$CONFIG_FILE" <<EOF
// Generated by docker/entrypoint.sh from MINA_EXPLORER_* env vars.
window.__MINA_EXPLORER_CONFIG__ = {
  defaultNetwork: $DEFAULT_JS,
  networks: $NETWORKS_JSON
};
EOF

echo "[mina-explorer] runtime config written to $CONFIG_FILE"
echo "[mina-explorer]   defaultNetwork: ${DEFAULT_NETWORK:-<unset>}"
echo "[mina-explorer]   networks: $(printf '%s' "$NETWORKS_JSON" | jq -c 'keys' 2>/dev/null || echo '[]')"
